### ISSUE TITLE
Improve ADA compliance

### ISSUE THREAD

**Issue by cecilia-donnelly** [SolutionGuidance/psm#467]
This is a placeholder that will get more content after we complete #415 and know what our first steps toward improvement are.

**Comment by brainwane** [comment]
Relevant issues:

- [ ] #376
- [ ] #507
- [ ] #508
- [ ] #509
- [ ] #510
- [ ] #511
- [ ] #512
- [ ] #513
- [ ] #514

**Comment by PaulMorris** [comment]
Here's a categorization of these issues by difficulty/time commitment.

**Straightforward changes in small and well determined number of places**

#517 - Add language declaration to HTML header
#514 - Fix color contrast in headers and footers for accessibility
#516 - Duplicate ID for Next button on Summary Information page during enrollment

**Straightforward uniform changes in indefinite number of places**

#376 - Remove right-justified colons between labels and fields on forms

**Non-uniform changes in indefinite number of places**

#512 - Logically nest header elements
#507 - Fix anchors that have no link content

**Non-uniform changes, requiring content considerations, indefinite number of places**

#509 - Improve accessibility (e.g. alt text) for images
#513 - Ensure screenreaders can see headers on tables
#508 - Provide descriptive labels/instructions for user input in forms

**More involved issues**

#510 - Improve keyboard navigation for forms & elements
#511 - Describe form input error to user in text

**Comment by PaulMorris** [comment]
Here are some notes I made as I was looking through them.

#509 - Some of these issues were the result of page export process. (Only 23 `img` tags.)
#507 - Many may be fixed by using tags other than `a` like `button` etc.
#513 - This includes several issues related to tables:
       - use summary attribute on table element for data tables
       - use caption element for data tables
       - use heading markup for headings
#510 - See #65 on use of javascript in forms.

**Comment by cecilia-donnelly** [comment]
@PaulMorris, am I right to say that we are focusing on the following, most important problems:

- [ ] #553 - Use accessible submit button on all forms (see PRs #567, #570, #573)
- [ ] #554 - Give form input elements a name for accessibility
- [x] #514 - Fix color contrast in headers and footers for accessibility
- [ ] #507 - Fix anchors that have no link content
- [ ] #509 - Improve accessibility (e.g. alt text) for images

**Comment by PaulMorris** [comment]
@cecilia-donnelly , yes, thanks for updating the status here.  These five are the issues that I've seen flagged as errors using the HTML_CodeSniffer.  The others are either categorized as warnings (under the AA standard) or else are more rare and I have not run into them when testing pages.  (e.g. I think #376 and #512 are warnings.)

On the color contrast, I should open a new issue since the one in #514 is fixed, but a different one was found.  (Blue link color on light blue table rows.)

**Comment by cecilia-donnelly** [comment]
Closing this.  We have definitely improved our ADA compliance.  We have [other, more specific issues](https://github.com/SolutionGuidance/psm/issues?q=is%3Aissue+is%3Aopen+accessibility+label%3Aaccessibility) open for lingering accessibility issues.
